FROM python:3.11-slim

RUN apt-get update && apt-get upgrade -y

COPY requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /app

EXPOSE 8051

COPY assets assets
COPY src src
COPY dashboard-lite/pages pages
COPY dashboard-lite/app.py .
COPY config.py .

CMD ["python", "app.py"]
