FROM python:3.11-slim

ENV http_proxy http://proxy-chain.xxx.com:911/
ENV https_proxy http://proxy-chain.xxx.com:912/

RUN apt-get update && apt-get upgrade -y

COPY requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /app

EXPOSE 8050

COPY . .

CMD ["python", "app.py"]
