FROM python:3.11-slim

ENV http_proxy http://proxy-chain.xxx.com:911/
ENV https_proxy http://proxy-chain.xxx.com:912/

RUN apt-get update && apt-get upgrade -y

COPY requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /app

EXPOSE 8051

COPY assets assets
COPY src src
COPY dashboard-lite/pages pages
COPY dashboard-lite/app.py .
COPY config.py .

CMD ["python", "app.py"]
